# Generated by Django 4.0.6 on 2022-08-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='p_name',
        ),
    ]
