# Generated by Django 4.0.6 on 2022-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0002_rename_name_products_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
