# Generated by Django 4.0.6 on 2022-08-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
